In [76]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
plt.style.use('fivethirtyeight')
from pylab import rcParams
%matplotlib inline
%config InlineBackend.figure_format='svg'

Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [77]:
a=np.random.randint(12,24,12)
a

array([22, 21, 23, 23, 14, 23, 18, 15, 20, 14, 16, 14])

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [78]:
array_a=[]
array_r=[(2,6),(3,4),(4,3),(6,2),(12,1)]
for el in array_r:
    a.resize(el)
    array_a.append(a.copy())
for el in array_a:
    print(type(el))
    print(el)

<class 'numpy.ndarray'>
[[22 21 23 23 14 23]
 [18 15 20 14 16 14]]
<class 'numpy.ndarray'>
[[22 21 23 23]
 [14 23 18 15]
 [20 14 16 14]]
<class 'numpy.ndarray'>
[[22 21 23]
 [23 14 23]
 [18 15 20]
 [14 16 14]]
<class 'numpy.ndarray'>
[[22 21]
 [23 23]
 [14 23]
 [18 15]
 [20 14]
 [16 14]]
<class 'numpy.ndarray'>
[[22]
 [21]
 [23]
 [23]
 [14]
 [23]
 [18]
 [15]
 [20]
 [14]
 [16]
 [14]]


Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [79]:
array_a=[]
array_r=[(2,-1),(3,-1),(4,-1),(-1,2),(-1,1)]
for el in array_r:
    array_a.append(a.reshape(el))
for el in array_a:
    print(type(el))
    print(el)

<class 'numpy.ndarray'>
[[22 21 23 23 14 23]
 [18 15 20 14 16 14]]
<class 'numpy.ndarray'>
[[22 21 23 23]
 [14 23 18 15]
 [20 14 16 14]]
<class 'numpy.ndarray'>
[[22 21 23]
 [23 14 23]
 [18 15 20]
 [14 16 14]]
<class 'numpy.ndarray'>
[[22 21]
 [23 23]
 [14 23]
 [18 15]
 [20 14]
 [16 14]]
<class 'numpy.ndarray'>
[[22]
 [21]
 [23]
 [23]
 [14]
 [23]
 [18]
 [15]
 [20]
 [14]
 [16]
 [14]]


Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

Ответ: Нет.

In [80]:
array_a[4]

array([[22],
       [21],
       [23],
       [23],
       [14],
       [23],
       [18],
       [15],
       [20],
       [14],
       [16],
       [14]])

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [81]:
a=np.random.randn(3,4)
print(a.size)
a

12


array([[-0.52512285,  1.91277127, -2.02671962,  1.11942361],
       [ 0.77919263, -1.10109776,  1.13022819,  0.37311891],
       [-0.38647295, -1.15877024,  0.56611283, -0.70445345]])

In [82]:
b=a.flatten()
print(b.size)
b

12


array([-0.52512285,  1.91277127, -2.02671962,  1.11942361,  0.77919263,
       -1.10109776,  1.13022819,  0.37311891, -0.38647295, -1.15877024,
        0.56611283, -0.70445345])

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [83]:
a=np.arange(20,0,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

Ответ: нет разницы.

In [84]:
b=np.array([np.arange(20,1,-2)])
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [85]:
a=np.zeros((3,2))
b=np.ones((2,2))
v=np.vstack((a,b))
print(f'v.size = {v.size}')
v

v.size = 10


array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [86]:
a=np.arange(0,12)
A=a.reshape((4,3))
At=A.T
B=A.dot(At)
print(f'B.size = {B.size}')
B


B.size = 16


array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [87]:
np.random.seed(42)

Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [88]:
c=np.random.normal(0,16,size=16)
c

array([  7.94742645,  -2.21222882,  10.36301661,  24.3684777 ,
        -3.746454  ,  -3.74619131,  25.26740505,  12.27895567,
        -7.51159017,   8.6809607 ,  -7.41468308,  -7.45167606,
         3.87139635, -30.61248391, -27.59868532,  -8.99660047])

Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [89]:
C=c.reshape(4,-1)
D=(C+B)*10
det_D=np.linalg.det(D)
print(det_D)
r_D=np.linalg.matrix_rank(D)
print(r_D)
D_inv=np.linalg.inv(D)
D_inv

-9730985070.93442
4


array([[ 0.02319072, -0.00027786,  0.00438988, -0.00739875],
       [ 0.00530374, -0.00173236,  0.00447832, -0.00335278],
       [ 0.00449427,  0.00395587,  0.00028305, -0.00287513],
       [-0.00732185, -0.00191528, -0.00211236,  0.00410229]])

Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [90]:
D_inv[D_inv<0]=0
D_inv[D_inv>0]=1
print(f'B\n{B}')
print(f'C\n{C}')
print(f'D_inv\n{D_inv}')
E=D_inv.copy()
E[np.where(D_inv==1)]=B[np.where(D_inv==1)]
E[np.where(D_inv==0)]=C[np.where(D_inv==0)]
E

B
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
C
[[  7.94742645  -2.21222882  10.36301661  24.3684777 ]
 [ -3.746454    -3.74619131  25.26740505  12.27895567]
 [ -7.51159017   8.6809607   -7.41468308  -7.45167606]
 [  3.87139635 -30.61248391 -27.59868532  -8.99660047]]
D_inv
[[1. 0. 1. 0.]
 [1. 0. 1. 0.]
 [1. 1. 1. 0.]
 [0. 0. 0. 1.]]


array([[  5.        ,  -2.21222882,  23.        ,  24.3684777 ],
       [ 14.        ,  -3.74619131,  86.        ,  12.27895567],
       [ 23.        ,  86.        , 149.        ,  -7.45167606],
       [  3.87139635, -30.61248391, -27.59868532, 302.        ]])