In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
plt.style.use('fivethirtyeight')
from pylab import rcParams
%matplotlib inline
%config InlineBackend.figure_format='svg'

Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [2]:
a=np.random.randint(12,24,12)
a

array([23, 17, 17, 22, 23, 15, 18, 17, 17, 13, 16, 22])

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [3]:
array_a=[]
array_r=[(2,6),(3,4),(4,3),(6,2),(12,1)]
for el in array_r:
    a.resize(el)
    array_a.append(a.copy())
for el in array_a:
    print(type(el))
    print(el)

<class 'numpy.ndarray'>
[[23 17 17 22 23 15]
 [18 17 17 13 16 22]]
<class 'numpy.ndarray'>
[[23 17 17 22]
 [23 15 18 17]
 [17 13 16 22]]
<class 'numpy.ndarray'>
[[23 17 17]
 [22 23 15]
 [18 17 17]
 [13 16 22]]
<class 'numpy.ndarray'>
[[23 17]
 [17 22]
 [23 15]
 [18 17]
 [17 13]
 [16 22]]
<class 'numpy.ndarray'>
[[23]
 [17]
 [17]
 [22]
 [23]
 [15]
 [18]
 [17]
 [17]
 [13]
 [16]
 [22]]


Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [4]:
array_a=[]
array_r=[(2,-1),(3,-1),(4,-1),(-1,2),(-1,1)]
for el in array_r:
    array_a.append(a.reshape(el))
for el in array_a:
    print(type(el))
    print(el)

<class 'numpy.ndarray'>
[[23 17 17 22 23 15]
 [18 17 17 13 16 22]]
<class 'numpy.ndarray'>
[[23 17 17 22]
 [23 15 18 17]
 [17 13 16 22]]
<class 'numpy.ndarray'>
[[23 17 17]
 [22 23 15]
 [18 17 17]
 [13 16 22]]
<class 'numpy.ndarray'>
[[23 17]
 [17 22]
 [23 15]
 [18 17]
 [17 13]
 [16 22]]
<class 'numpy.ndarray'>
[[23]
 [17]
 [17]
 [22]
 [23]
 [15]
 [18]
 [17]
 [17]
 [13]
 [16]
 [22]]


Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

Ответ: Нет.

In [5]:
array_a[4]

array([[23],
       [17],
       [17],
       [22],
       [23],
       [15],
       [18],
       [17],
       [17],
       [13],
       [16],
       [22]])

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [6]:
a=np.random.randn(3,4)
print(a.size)
a

12


array([[ 1.02341662, -1.97819651, -0.47996806, -1.79324069],
       [ 1.29317858,  0.34231974, -1.3373473 ,  0.32360688],
       [ 0.39782498, -2.13247384, -1.59534344,  0.03473775]])

In [7]:
b=a.flatten()
print(b.size)
b

12


array([ 1.02341662, -1.97819651, -0.47996806, -1.79324069,  1.29317858,
        0.34231974, -1.3373473 ,  0.32360688,  0.39782498, -2.13247384,
       -1.59534344,  0.03473775])

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [8]:
a=np.arange(20,0,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [9]:
b=np.array([np.arange(20,1,-2)])
print(a)
print(b)

[20 18 16 14 12 10  8  6  4  2]
[[20 18 16 14 12 10  8  6  4  2]]


Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [10]:
a=np.zeros((3,2))
b=np.ones((2,2))
v=np.vstack((a,b))
print(f'v.size = {v.size}')
v

v.size = 10


array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [11]:
a=np.arange(0,12)
A=a.reshape((4,3))
At=A.T
B=A.dot(At)
print(f'B.size = {B.size}')
print(f'Квадратная матрица В - Симметрична относительно главной диагонили => Bt = B\n{B.T}\n=\n{B}')



B.size = 16
Квадратная матрица В - Симметрична относительно главной диагонили => Bt = B
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
=
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [12]:
np.random.seed(42)

Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [13]:
c=np.arange(0,16,1)
np.random.shuffle(c)
c

array([ 0,  1,  5, 14, 13, 11,  8,  9,  2, 15,  4,  7, 10, 12,  3,  6])

Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [14]:

C=c.reshape(4,-1)
D=(C+B)*10
det_D=np.linalg.det(D)
print(det_D)
r_D=np.linalg.matrix_rank(D)
print(r_D)
D_inv=np.linalg.inv(D)
D_inv

-643339999.9999989
4


array([[ 0.00675537,  0.01095377, -0.0017518 , -0.00442223],
       [ 0.00650356,  0.00964809,  0.01642211, -0.01675164],
       [-0.03435198, -0.01515839, -0.01948581,  0.0254329 ],
       [ 0.02022881,  0.0048901 ,  0.0066963 , -0.00953772]])

Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [15]:
D_inv[D_inv<0]=0
D_inv[D_inv>0]=1
print(f'B\n{B}')
print(f'C\n{C}')
print(f'D_inv\n{D_inv}')
E=D_inv.copy()
E[np.where(D_inv==1)]=B[np.where(D_inv==1)]
E[np.where(D_inv==0)]=C[np.where(D_inv==0)]
E

B
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
C
[[ 0  1  5 14]
 [13 11  8  9]
 [ 2 15  4  7]
 [10 12  3  6]]
D_inv
[[1. 1. 0. 0.]
 [1. 1. 1. 0.]
 [0. 0. 0. 1.]
 [1. 1. 1. 0.]]


array([[  5.,  14.,   5.,  14.],
       [ 14.,  50.,  86.,   9.],
       [  2.,  15.,   4., 212.],
       [ 32., 122., 212.,   6.]])